#!/bin/bash
#
# Copy text to https://ip.pla1.net/Misc/Pastebin
#
if [[ $# -eq 1 && -f $1 ]]
then
  text=$(cat "$1")
else
  text="$*"
fi
curl --data-urlencode "text=$text" https://ip.pla1.net/Misc/Pastebin
