#!/bin/bash
#
# Converts MAC address to the three difference formats. 1. XX:XX:XX:XX:XX:XX 2. XXXX.XXXX.XXXX 3. XX-XX-XX-XX-XX-XX
# Copies the output to the clipboard via Parcellite the clipboard manager.
#
MAC="$1"
MAC=${MAC//[:|\-|.]/}
LENGTH=${#MAC}
if [[ $LENGTH -ne 12 ]]; then
  echo "Length of the unformatted MAC address should equal 12 but it is: $LENGTH"
  exit -1
fi
MAC1=${MAC:0:2}:${MAC:2:2}:${MAC:4:2}:${MAC:6:2}:${MAC:8:2}:${MAC:10:2}
MAC2=${MAC:0:2}-${MAC:2:2}-${MAC:4:2}-${MAC:6:2}-${MAC:8:2}-${MAC:10:2}
MAC3=${MAC:0:4}.${MAC:4:4}.${MAC:8:4}
echo "$MAC1" | tr '[:lower:]' '[:upper:]' | parcellite
sleep 1
echo "$MAC2"  | tr '[:lower:]' '[:upper:]' | parcellite
sleep 1
echo "$MAC3"  | tr '[:lower:]' '[:upper:]' | parcellite
sleep 1
echo "$MAC"  | tr '[:lower:]' '[:upper:]' | parcellite
