#!/bin/bash
#
# Create some symbolic links
#
if [ ! -d ~/bin ]
then
  mkdir ~/bin
fi

for command in ctrlv ctrlc mac mute
do
  if [ ! -f ~/bin/$command ]
  then
    echo "Creating symbolic link for command $command"
    ln -s ~/utils/$command ~/bin/$command
  fi
done
