#!/bin/bash
#
# Play a HDHomeRun channel. Pass the channel call sign. On the initial run this will ask you
# for the IP address of the HDHomeRun device and store the IP address in ~/.hdhrIpAddress.
#
# This script lives here: https://github.com/pla1/utils/blob/master/tv
#
# Wikipedia TV station call signs.
# http://en.wikipedia.org/wiki/List_of_television_stations_in_the_United_States_by_call_sign_(initial_letter_K)
# http://en.wikipedia.org/wiki/List_of_television_stations_in_the_United_States_by_call_sign_(initial_letter_W)
#
# Uses mplayer. Change the last line in this script to your favorite media player.
#
CURLY="[{}]"
CR="\n"
BRACKETS="[\]\[]"
IP=$(cat ~/.hdhrIpAddress)
if [ -z "$IP" ]
then
  read -p "Key the IP address of the HDHomeRun and press ENTER " IP
  echo "$IP" > ~/.hdhrIpAddress
fi
callSign="$1"
lineup=$(curl --silent "http://$IP/lineup.json")
if [[ "$lineup" != *"GuideNumber"* ]]
then
  rm -f ~/.hdhrIpAddress
  echo -e "\n\nMissing channel lineup. Check the IP address $IP. Also make sure you have the latest firmware on your HDHomeRun device. https://www.silicondust.com/support/downloads/\n\n" 
  exit 1
fi
newLineup="${lineup//$CURLY/$CR}"
lineup="${newLineup//$BRACKETS/}"
line=$(echo -e "$lineup" | grep -i "$callSign")
if [ -z "$line" ]
then
  echo "Call sign \"$callSign\" not found."
  exit 1
fi
urlString=$(echo "$line" | cut -d , -f3)
url=$(echo "$urlString" | cut -d \" -f4)
echo -e "\n\nPlaying $url\n\n"
/usr/bin/mplayer "$url"
